title: Hairclub
description: "Time-tested, proven solutions for hair regrowth, replacement, and restoration. 40 years of experience."
timezone: UTC
port: 2000
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
minima:
  date_format: "%b %-d, %Y"
sass:
  style: compressed